Implemented GetPackageViaIDController and GetPackagesFromRegistryController
Collaborative-SWE-at-Purdue/Registry pull request #104
Opened 2024-10-30 10:51 UTC by bkanter-purdue

Closes #25

2024-10-30 16:56 UTC, bkanter-purdue commented
Updated the branch to send base64 string

2024-11-02 15:39 UTC, j-leidy requested changes

2024-11-02 15:39 UTC, j-leidy commented on BE/src/Controllers/GetPackageControllers.ts
> +                .then((queriedPackage) => { // Have to do it this way since inside a forEach
```ts
const queryConditions = requestedPackages.map((requestedPackageInfo) => ({
            "metadata.Name": requestedPackageInfo.Name,
            "metadata.Version": requestedPackageInfo.Version,
        }));
const results = await PackageModel.find({ $or: queryConditions });
```

 You will still have to transform to the proper return type. Please use this to eliminate the loop.

2024-11-06 00:28 UTC, BellDorian commented
This is not ready.

2024-11-06 00:28 UTC, closed without merging