Adding functional ModEval to dev.
Collaborative-SWE-at-Purdue/Registry pull request #91
Opened 2024-10-25 17:28 UTC by BellDorian

- All preexisting scores are operational
- Desired functionality is there
- Again, I have no clue about what test subscores should be. If there are previously-existing tests for that, they can be repurposed here.

2024-10-25 21:37 UTC, j-leidy requested changes

2024-10-25 21:37 UTC, j-leidy commented on BE/Tests/Evaluator.spec.ts
npm run test will show that the describe block can't be async

 I modified this on dev to pass

2024-10-25 22:29 UTC, BellDorian commented on BE/Tests/Evaluator.spec.ts
Ok, I looked at what you had and made some modifications. What do you think now? idk how to actually run the tests on my end so I haven't actually executed them.

2024-10-26 01:05 UTC, j-leidy approved these changes
LGTM

2024-10-26 01:06 UTC, merged